### ISSUE TITLE
Token error 404 even though it's valid

### ISSUE THREAD

**Issue by marco79cgn** [beep-projects/telegram.bot#1]
My telegram bot works as intended and the token is valid but I can't use this nice project here because it keeps telling me otherwise: 
```
telegram.bot --test_token "613********:AAH*********"
{"ok":false,"error_code":404,"description":"Not Found"}
```
I'm running it on a Raspberry Pi (Raspbian OS Bullseye) and both curl and jq have already been installed. 

Any ideas?

**Comment by beep-projects** [comment]
Hi Marco,

great that you give the project a try.
The --test_token  option simply calls the getMe function of the bot API

What do you see if you replace {YOUR_BOT_TOKEN} with your token and open the URL in your browser? 
https://api.telegram.org/bot{YOUR_BOT_TOKEN}/getMe

**Comment by beep-projects** [comment]
Now I see the problem, my bad. I did it wrong in the documentation.
You actually have to pass the bot token using the  --bottoken option.
So the correct command above would be
`telegram.bot --test_token --bottoken "613********:AAH*********"`

**Comment by beep-projects** [comment]
I fixed the test for --test_token and pushed the change. Now it issues a warning if --bottoken is missing.
